spring:
  application:
    name: mithril-forge
    url: ${APPLICATION_URL:localhost:5173}
    secret: ${SECRET:very-secret-string}
  session:
    jdbc:
      initialize-schema: always
  docker:
    compose:
      file: ../compose.yaml
      enabled: true
  flyway:
    baseline-on-migrate: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
  devtools:
    restart:
      exclude: static/**
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    from: ${SMTP_FROM:noreply@example.com}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: ${SMTP_START_TLS:false}

sentry:
  enabled: false

server:
  port: 8080
